#!/usr/bin/env bash

# Copyright (C) 2016 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

arguments() {
	project_arguments_targets "$project" "$@"
}

usage() {
	project_usage_actions "$project" "checkout"
	project_usage_arguments "$project" "$@"
}

download() {
	local repository=$project

	project_download_git "$project" "$repository" "https://chromium.googlesource.com/chromiumos/platform/vboot_reference https://review.coreboot.org/vboot.git https://github.com/coreboot/vboot.git" "$@"
}

download_check() {
	project_download_check_git "$project" "$repository" "$@"
}

extract() {
	project_extract "$project" "$@"
}

extract_check() {
	project_extract_check "$project" "$@"
}

update() {
	local repository=$project

	project_update_git "$project" "$repository" "$@"
}

update_check() {
	local repository=$project

	project_update_check_git "$project" "$repository" "$@"
}

checkout() {
	local repository=$project

	if git_project_check "$repository"
	then
		git_project_checkout "$project" "$repository" "$@"
	fi
}

build() {
	local target=$1

	local repository=$project

	project_sources_directory_missing_empty_error "$project" "$repository" "$@"

	if git_project_check "$repository"
	then
		git_project_checkout "$project" "$repository" "$@"
	fi

	if [[ "$target" = "tools" ]]
	then
		local sources_path=$(project_sources_path "$project" "$repository" "$@")
		local build_path=$(project_build_path "$project" "$@")

		mkdir -p "$build_path"

		make -C "$sources_path" BUILD="$build_path" -j$TASKS "host_stuff"
		make -C "$sources_path" BUILD="$build_path" -j$TASKS "host_stuff"

		cp -r "$sources_path/tests/devkeys" "$build_path"
	fi
}

build_check() {
	local target=$1

	if [[ "$target" = "tools" ]]
	then
		project_build_check "$project" "$@"
	fi
}

install() {
	local target=$1

	if [[ "$target" = "tools" ]]
	then
		project_install "$project" "$@"
	fi
}

install_check() {
	local target=$1

	if [[ "$target" = "tools" ]]
	then
		project_install_check "$project" "$@"
	fi
}

release() {
	local target=$1

	local repository=$project

	if [[ "$target" = "tools" ]]
	then
		project_release_install_archive "$project" "$TOOLS" "$@"
	fi

	project_release_sources_git "$project" "$repository" "$@"
}

release_check() {
	local target=$1

	local repository=$project

	if [[ "$target" = "tools" ]]
	then
		project_release_install_archive_check "$project" "$TOOLS" "$@"
	fi

	project_release_check_sources_git "$project" "$repository" "$@"
}

clean() {
	project_clean "$project" "$@"
}
