#!/usr/bin/env bash

# Copyright (C) 2016 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage() {
	project_usage_actions "$project"
}

install() {
	local install_path=$(project_install_path "$project" "$@")

	project_install "$project" "$@"
}

install_check() {
	project_install_check "$project" "$@"
}

release() {
	project_release_install "$project" "$TOOLS" "$@"
}

release_check() {
	project_release_install_check "$project" "$TOOLS" "$@"
}

clean() {
	project_clean "$project" "$@"
}
