#!/usr/bin/env bash

#  helper script: Downloads MemTest86+ and patches it
#
#	Copyright (C) 2014, 2015 Leah Rowe <info@minifree.org>
#	Copyright (C) 2015 Joseph Michael Thompson <jmt@josepht.me>
#	Copyright (C) 2015 Klemens Nanni <contact@autoboot.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

# Get the last version of MemTest86+ used, apply patches, build it.

# Remove the old version that may exist
# ------------------------------------------------------------------------------

printf "Downloading MemTest86+\n"

rm -Rf "memtest86plus/"

# Get latest memtest86+:
# ------------------------------------------------------------------------------

# download it using wget
wget http://www.memtest.org/download/5.01/memtest86+-5.01.tar.gz

if [ "$(sha512sum memtest86+-5.01.tar.gz | cut -c1-128)" = "d872db35ef733ec8f49094251f2bf6b98cc80eb06d04044be3aecf28d534f24ba293a08b9979b112dbd07cf27368148939a33a32c7010fc9581a3a5b150c94d7" ]; then
	printf "Valid checksum for memtest86plus\n"
else
	rm -f "memtest86+-5.01.tar.gz"
	printf "Invalid checksum for memtest86plus\n"
	exit 1
fi

# extract it
tar -xzf "memtest86+-5.01.tar.gz"

# delete the tar file (no longer needed)
rm -f "memtest86+-5.01.tar.gz"

# make direcotory name consistent
mv "memtest86+-5.01/" "memtest86plus/"

# Apply necessary patches
# ------------------------------------------------------------------------------

(
cd "memtest86plus/"
for patch in ../resources/memtest86plus/patch/*; do
	patch < "${patch}"
done
)

printf "\n\n"
