#!/usr/bin/env bash

# Copyright (C) 2019 Andrew Robbins <contact@andrewrobbins.info>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage() {
	project_usage_actions "$project"
}

collect() {
	project_dependencies "$@"
}

download() {
	project_dependencies_action_arguments "$action" "$@"
}

extract() {
	project_dependencies_action_arguments "$action" "$@"
}

update() {
	project_dependencies_action_arguments "$action" "$@"
}

build() {
	project_dependencies_action_arguments "$action" "$@"
}

install() {
	project_dependencies_action_arguments "$action" "$@"
}

release() {
	project_dependencies_action_arguments "$action" "$@"
}

clean() {
	project_dependencies_action_arguments "$action" "$@"
}
